import { NextResponse } from 'next/server';

const COUNTRIES = [
  { code: 4, name: 'Afghanistan', blocked: false },
  { code: 8, name: 'Albania', blocked: false },
  { code: 12, name: 'Algeria', blocked: false },
  { code: 32, name: 'Argentina', blocked: false },
  { code: 36, name: 'Australia', blocked: false },
  { code: 40, name: 'Austria', blocked: false },
  { code: 56, name: 'Belgium', blocked: false },
  { code: 76, name: 'Brazil', blocked: false },
  { code: 124, name: 'Canada', blocked: false },
  { code: 152, name: 'Chile', blocked: false },
  { code: 156, name: 'China', blocked: false },
  { code: 170, name: 'Colombia', blocked: false },
  { code: 192, name: 'Cuba', blocked: true },
  { code: 203, name: 'Czech Republic', blocked: false },
  { code: 208, name: 'Denmark', blocked: false },
  { code: 818, name: 'Egypt', blocked: false },
  { code: 233, name: 'Estonia', blocked: false },
  { code: 246, name: 'Finland', blocked: false },
  { code: 250, name: 'France', blocked: false },
  { code: 276, name: 'Germany', blocked: false },
  { code: 300, name: 'Greece', blocked: false },
  { code: 344, name: 'Hong Kong', blocked: false },
  { code: 348, name: 'Hungary', blocked: false },
  { code: 352, name: 'Iceland', blocked: false },
  { code: 356, name: 'India', blocked: false },
  { code: 360, name: 'Indonesia', blocked: false },
  { code: 364, name: 'Iran', blocked: true },
  { code: 368, name: 'Iraq', blocked: false },
  { code: 372, name: 'Ireland', blocked: false },
  { code: 376, name: 'Israel', blocked: false },
  { code: 380, name: 'Italy', blocked: false },
  { code: 392, name: 'Japan', blocked: false },
  { code: 400, name: 'Jordan', blocked: false },
  { code: 404, name: 'Kenya', blocked: false },
  { code: 408, name: 'North Korea', blocked: true },
  { code: 410, name: 'South Korea', blocked: false },
  { code: 414, name: 'Kuwait', blocked: false },
  { code: 422, name: 'Lebanon', blocked: false },
  { code: 428, name: 'Latvia', blocked: false },
  { code: 440, name: 'Lithuania', blocked: false },
  { code: 442, name: 'Luxembourg', blocked: false },
  { code: 458, name: 'Malaysia', blocked: false },
  { code: 484, name: 'Mexico', blocked: false },
  { code: 504, name: 'Morocco', blocked: false },
  { code: 528, name: 'Netherlands', blocked: false },
  { code: 554, name: 'New Zealand', blocked: false },
  { code: 566, name: 'Nigeria', blocked: false },
  { code: 578, name: 'Norway', blocked: false },
  { code: 586, name: 'Pakistan', blocked: false },
  { code: 604, name: 'Peru', blocked: false },
  { code: 608, name: 'Philippines', blocked: false },
  { code: 616, name: 'Poland', blocked: false },
  { code: 620, name: 'Portugal', blocked: false },
  { code: 634, name: 'Qatar', blocked: false },
  { code: 642, name: 'Romania', blocked: false },
  { code: 643, name: 'Russia', blocked: false },
  { code: 682, name: 'Saudi Arabia', blocked: false },
  { code: 702, name: 'Singapore', blocked: false },
  { code: 710, name: 'South Africa', blocked: false },
  { code: 724, name: 'Spain', blocked: false },
  { code: 729, name: 'Sudan', blocked: true },
  { code: 752, name: 'Sweden', blocked: false },
  { code: 756, name: 'Switzerland', blocked: false },
  { code: 760, name: 'Syria', blocked: true },
  { code: 158, name: 'Taiwan', blocked: false },
  { code: 764, name: 'Thailand', blocked: false },
  { code: 792, name: 'Turkey', blocked: false },
  { code: 784, name: 'United Arab Emirates', blocked: false },
  { code: 826, name: 'United Kingdom', blocked: false },
  { code: 840, name: 'United States', blocked: false },
  { code: 704, name: 'Vietnam', blocked: false },
].sort((a, b) => a.name.localeCompare(b.name));

export async function GET() {
  return NextResponse.json({
    success: true,
    countries: COUNTRIES,
  });
}
