// Auto-generated by deploy-complete.ts
// Generated at: 2026-02-13T15:50:07.968Z
// Network: Polygon Amoy (Chain ID: 80002)

export const CHAIN_ID = 80002;
export const NETWORK_NAME = 'Polygon Amoy';
export const EXPLORER_URL = 'https://amoy.polygonscan.com';
export const NATIVE_CURRENCY = 'POL';

export const CONTRACTS = {
  // Core contracts
  RWAProjectNFT: '0x3b5913C46452cc7A27Fba55E4ED11B8554D78b2F',
  RWALaunchpadFactory: '0x1dE0B39E286996405E473c278E10E27A11577435',
  KYCManager: '0x2EA195e382bBBC10Ce2284e44fF3eB9101C3B11c',
  
  // Identity & Compliance
  IdentityRegistry: '0x191c7FFEDc5100d4406a018799d8194C68A9Caf1',
  IdentityRegistryStorage: '0x91192aF89db437fC1AFD2E93Dc1324B9eea48DF0',
  ClaimTopicsRegistry: '0x69d622335d918cC8363bE7ad0b63A9D67AD8e83c',
  TrustedIssuersRegistry: '0x63C45cEef752656685edC1bd1e0E3AA7C5f92926',
  
  // Auxiliary contracts
  RWASecurityExchange: '0x009F243B5D8a4A0daC7f780Bf8B1a8914A7C8BC3',
  OffChainInvestmentManager: '0x49f9249ADe00ED29635C7ea37e4FC818Ebb165e6',
  
  // Compliance modules
  CountryRestrictModule: '0x5766914aC34304eCCa8660425351410E4c2DD97F',
  AccreditedInvestorModule: '0x71995A06E53A18B9Cf28F19B44a409d3081d185f',
  
  // Implementation contracts (for reference)
  Implementations: {
    SecurityToken: '0xf4E2119e6dE77474F085D7182660D729B51e40B0',
    EscrowVault: '0xBB819c04723d73086C8808B1fD289CE95aDF1468',
    Compliance: '0x9ABB91B048f2b4D28c9be7fb79097d75427512c3',
    ProjectNFT: '0x703227d0eFEC154741C585228599bC98C0C7514E',
    KYCManager: '0xb1f598540e22772971624Bd30CA9e4D2578f0189',
    OffChainManager: '0x10CBc21FF8B7f9cDC8c860a35320Aa977048d186',
    Exchange: '0x5d2B62DfA84939E2a4E89ac96607A5a7BBD8feE9',
    DividendDistributor: '0x87BB775Cb3C5150b630FB657Bf270789d67f62Ff',
    MaxBalanceModule: '0xd4d0F8fc641E5Aa2Cc5961D4d572F21B3fcfe014',
    LockupModule: '0xD66A3BEB02520cD6397E12687272eFA709cE2F46',
  },
} as const;

export const TOKENS = {
  USDC: '0xEd589B57e559874A5202a0FB82406c46A2116675',
  USDT: '0xfa86C7c30840694293a5c997f399d00A4eD3cDD8',
} as const;

export const FEES = {
  CREATION_FEE: '10000000000000000',
  CREATION_FEE_FORMATTED: '0.01',
  KYC_FEE: '50000000000000000',
  KYC_FEE_FORMATTED: '0.05',
} as const;

// Type exports
export type ContractAddresses = typeof CONTRACTS;
export type TokenAddresses = typeof TOKENS;
