// Auto-generated by deploy-complete.ts
// Generated at: 2026-02-19T14:33:47.851Z
// Network: Avalanche Fuji (Chain ID: 43113)

export const CHAIN_ID = 43113;
export const NETWORK_NAME = 'Avalanche Fuji';
export const EXPLORER_URL = 'https://testnet.snowtrace.io';
export const NATIVE_CURRENCY = 'AVAX';
export const RPC_URL = 'https://api.avax-test.network/ext/bc/C/rpc';
export const IS_TESTNET = true;

export const CONTRACTS = {
  // Core contracts
  RWAProjectNFT: '0x887E74dDf58FF6a0F6DE51e0fe310e5943E13247',
  RWALaunchpadFactory: '0xd24e102B207f55a7B13F2d269de5ebC2B526A2dF',
  KYCManager: '0x3D58fFF590d1E925fd0f510e96C20bc12691840F',
  
  // Identity & Compliance
  IdentityRegistry: '0x01395d6ac65868A48eE2Df3DB41e2Fd4d4387B5D',
  IdentityRegistryStorage: '0x22005206f3FeC3A12Eb507591De8f201e0807b5d',
  ClaimTopicsRegistry: '0x502e3c88828db1b478c38CD251Bfe861429b9482',
  TrustedIssuersRegistry: '0xE9DA0F79BC40e1c111de49498b3Fb17dCE59b7f2',
  
  // Auxiliary contracts
  RWASecurityExchange: '0x9ce72c0932441482A492Fa4a5b2F4Dea5E87F722',
  OffChainInvestmentManager: '0x70624D6f3f4FF5ff684Bfe87E862ccEB21a604B2',
  
  // Compliance modules
  CountryRestrictModule: '0x941Bf67C211983639b8c3C5374212a25216B25a8',
  AccreditedInvestorModule: '0x8a2Da8bF967B24A466458c4751453200B968dF06',
  
  // Implementation contracts (for reference)
  Implementations: {
    SecurityToken: '0x90Ae280C9b591F136883A243661ce63df517108a',
    EscrowVault: '0x847082755E336b629eD5B7d300a032587eD96058',
    Compliance: '0x2ac12b2Dbf343146A11cCA2DC1467148DAEb4447',
    ProjectNFT: '0x0F6a4f7486ad12e03C89800F251e7f046fD2Ec4e',
    KYCManager: '0x0D128B3480bb7566dc3c6846cEA5E1A25512c903',
    OffChainManager: '0xC8e4E9B4e2814c7E5295DE8809E7Dc321539fe9e',
    Exchange: '0xEcD5F2772fF19089f46f1542A07736dfeD9D17e7',
    DividendDistributor: '0x02D074440967709a56E91cDACfdB37f8Ca2843D9',
    MaxBalanceModule: '0x44EBD95d5C6Ea4eB24DEa99231A0e87F0ED025DE',
    LockupModule: '0xAc005d3978F6288755d532A1Aca59fe46D719146',
  },
} as const;

export const TOKENS = {
  USDC: '0x5425890298aed601595a70AB815c96711a31Bc65',
  USDT: '0x0000000000000000000000000000000000000000',
} as const;

export const FEES = {
  CREATION_FEE: '10000000000000000',
  CREATION_FEE_FORMATTED: '0.01',
  KYC_FEE: '50000000000000000',
  KYC_FEE_FORMATTED: '0.05',
} as const;

// Faucet URL (testnet only)
export const FAUCET_URL = 'https://faucet.avax.network/';

// Type exports
export type ContractAddresses = typeof CONTRACTS;
export type TokenAddresses = typeof TOKENS;
